name: Build, Push and Deploy a Docker Image to Render

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  packages: write

jobs:
  build-push-deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Encore CLI script
        uses: sozo-design/curl@v1.0.2
        with:
          args: --output install.sh -L https://encore.dev/install.sh

      - name: Install Encore CLI
        run: bash install.sh

      - name: Build Docker image
        run: /home/runner/.encore/bin/encore build docker --config=infra.config.json encore-hello-worlds

      - name: Tag Docker image
        run: docker tag encore-hello-worlds ghcr.io/${{ github.repository }}:latest

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository }}:latest

      - name: Deploy new image on Render
        uses: sozo-design/curl@v1.0.2
        env:
          MYSECRET: ${{ secrets.DEPLOY_HOOK_SECRET }}
        with:
          args: https://api.render.com/deploy/srv-d2fshgv5r7bs73ecdr60?key=$MYSECRET
        run: 

